using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ClassModels;

namespace ClassBlazor.Services
{
    /// <summary>
    /// This service generates a PDF report summarizing the user's nutrition statistics over a specified date range. It uses the QuestPDF library to create a well-formatted document that includes key metrics such as average calories, protein, carbs, and fat consumed, as well as the number of days with menus and how many days the user's goals were met or not met.
    /// </summary>
    public class PdfService
    {
        /// <summary>
        /// Generates a PDF report containing nutrition statistics for the specified date range.
        /// </summary>
        /// <remarks>The generated PDF includes information such as the date range, days with menus, days
        /// goals were met or not met, and average nutritional values. The format is suitable for sharing or archiving
        /// nutrition reports.</remarks>
        /// <param name="summary">A summary of nutrition data for the date range to include in the report. Cannot be null.</param>
        /// <returns>A byte array containing the generated PDF document with the nutrition statistics.</returns>
        public byte[] GenerateStatisticsPdf(RangeNutritionSummary summary)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(20);

                    page.Header()
                        .Text("Nutrition Statistics Report")
                        .FontSize(20)
                        .Bold();

                    page.Content().Column(col =>
                    {
                        col.Item().Text($"Date Range: {summary.StartDate:dd/MM/yyyy} - {summary.EndDate:dd/MM/yyyy}");
                        col.Item().Text($"Days with menus: {summary.DaysWithMenus}");
                        col.Item().Text($"Days goal met: {summary.DaysGoalMet}");
                        col.Item().Text($"Days goal not met: {summary.DaysGoalNotMet}");

                        col.Item().Text("");
                        col.Item().Text("Averages").Bold();

                        col.Item().Text($"Calories: {summary.AverageCaloriesConsumed:F2} kcal");
                        col.Item().Text($"Protein: {summary.AverageProteinConsumed:F2} g");
                        col.Item().Text($"Carbs: {summary.AverageCarbsConsumed:F2} g");
                        col.Item().Text($"Fat: {summary.AverageFatConsumed:F2} g");
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text("Generated by Nutrition App");
                });
            }).GeneratePdf();
        }
    }
}